version: '2.4'
services:
  front:
    build: .
    ports:
      - ${port}:2333
    restart: always
    read_only: true
    ipc: shareable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - challenge_conn_interval=${conn_interval}
      - challenge_token_timeout=${token_timeout}
      - challenge_timeout=${challenge_timeout}
      - challenge_pids_limit=${pids_limit}
      - challenge_cpus_limit=${cpus_limit}
      - challenge_mem_limit=${mem_limit}
      - challenge_docker_name=${challenge_docker_name}
      - challenge_read_only=${read_only}
      - TZ=Asia/Shanghai
